from ._per_dueling_double_deep_n_step_tree_backup import PERDuelingDoubleDeepNStepTreeBackup
from ._dueling_double_deep_q_network import DuelingDoubleDeepQNetwork
from ._per_dueling_double_deep_q_network import PERDuelingDoubleDeepQNetwork
from ._per_dueling_double_deep_sarsa import PERDuelingDoubleDeepSarsa
from ._per_dueling_double_deep_n_step_sarsa import PERDuelingDoubleDeepNStepSarsa

__all__ = ["PERDuelingDoubleDeepNStepTreeBackup", "DuelingDoubleDeepQNetwork", "PERDuelingDoubleDeepQNetwork",
 "PERDuelingDoubleDeepSarsa", "PERDuelingDoubleDeepNStepSarsa"]